/**
 * `@huaqiu/component-gen-server` — generation backend seam.
 *
 * The server never reimplements generation. It only defines the seam; the
 * `@huaqiu/dsh-tool-symbol-footprint` plugin provides the real implementation
 * (`createComponentGenBackend`) wired to its existing `runGenerate*` functions
 * + `SymbolFootprintEnv`. The standalone server builds the same backend from
 * the plugin's exports. Results are the raw tool-body outcomes:
 *
 *   symbol            → { status:'generated', kind:'symbol', fileUrl, filename, artifact?, … }
 *   extract-footprint → { status:'needs_confirmation', pkgType, fileName, dimensions, … }
 *                       | { status:'generated', kind:'footprint', autoGenerated:true, … }
 *   generate-footprint→ { status:'generated', kind:'footprint', pkgType, dimensions, … }
 *
 * `needs_auth` (the tool body's unauthenticated result) is mapped by the job
 * runner to a failed job with the `needs_auth` marker so the UI can re-trigger
 * login.
 */
import type { JobKind } from './types.js'

export interface GenerationExec {
  signal?: AbortSignal
}

export interface ComponentGenBackend {
  generateSymbol(args: { imageDataUrl: string; instruction?: string }, exec: GenerationExec): Promise<Record<string, unknown>>
  extractFootprint(args: { imageDataUrl: string; packageType?: string; instruction?: string }, exec: GenerationExec): Promise<Record<string, unknown>>
  generateFootprint(args: { packageType: string; fileName?: string; dimensions: Record<string, number> }, exec: GenerationExec): Promise<Record<string, unknown>>
}

export function kindLabel(kind: JobKind): 'symbol' | 'footprint' {
  return kind === 'symbol' ? 'symbol' : 'footprint'
}
