/**
 * `@huaqiu/component-gen-app` — completed-generation result stage.
 *
 * Renders the preview (from `ports.artifactContent`), a download action and a
 * note when the generation was auto-generated or degraded. DSH-agnostic.
 */
import { useCallback, useEffect, useState, type ReactElement } from 'react'
import type { ComponentGenPorts } from '../ports.js'
import type { Translate } from '../copy/index.js'
import { triggerDownload } from '../lib/ecad.js'
import { PreviewStage } from './PreviewStage.js'

export interface ResultStageProps {
  ports: ComponentGenPorts
  kind: 'symbol' | 'footprint'
  result: Record<string, unknown>
  t: Translate
  /** bump to force a re-render of the preview for a new result. */
  srcKey: string
}

function artifactIdOf(result: Record<string, unknown>): string | null {
  const art = result.artifact
  if (art && typeof art === 'object') {
    const id = (art as { id?: unknown }).id
    if (typeof id === 'string' && id) return id
  }
  return null
}

function filenameOf(result: Record<string, unknown>, kind: string): string {
  const f = result.filename
  if (typeof f === 'string' && f) return f
  return `generated.${kind === 'symbol' ? 'kicad_sym' : 'kicad_mod'}`
}

export function ResultStage({ ports, kind, result, t, srcKey }: ResultStageProps): ReactElement {
  const artifactId = artifactIdOf(result)
  const [content, setContent] = useState<string | null>(null)
  const [previewErr, setPreviewErr] = useState<string | null>(null)
  const [downloading, setDownloading] = useState(false)

  useEffect(() => {
    if (!artifactId) return
    let cancelled = false
    setContent(null)
    setPreviewErr(null)
    ports.artifactContent(artifactId)
      .then((text) => { if (!cancelled) setContent(text) })
      .catch((e) => { if (!cancelled) setPreviewErr(String((e as Error)?.message || e)) })
    return () => { cancelled = true }
  }, [artifactId, ports, srcKey])

  const download = useCallback(async (): Promise<void> => {
    setDownloading(true)
    try {
      if (artifactId) {
        const text = content ?? await ports.artifactContent(artifactId)
        triggerDownload(filenameOf(result, kind), text)
      } else {
        const fileUrl = result.fileUrl
        if (typeof fileUrl === 'string' && fileUrl) {
          window.open(fileUrl, '_blank', 'noopener')
        }
      }
    } finally {
      setDownloading(false)
    }
  }, [artifactId, content, ports, result, kind])

  const autoGenerated = result.autoGenerated === true
  const note = typeof result.note === 'string' ? result.note : null

  return (
    <div className="cga-panel">
      <div className="cga-panel__body">
        {autoGenerated ? <div className="cga-banner cga-banner--info">{t('footprint.directGenerated')}</div> : null}
        {content != null
          ? <PreviewStage kind={kind} content={content} srcKey={srcKey} t={t} />
          : previewErr
            ? <div className="cga-banner cga-banner--error">{t('app.error')}{previewErr}</div>
            : null}
        {note ? <div className="cga-banner cga-banner--info">{note}</div> : null}
        <div className="cga-actions">
          <button type="button" className="cga-btn cga-btn--primary" onClick={() => void download()} disabled={downloading}>
            {kind === 'symbol' ? t('symbol.download') : t('footprint.download')}
          </button>
        </div>
      </div>
    </div>
  )
}
